### PR TITLE
Fix example in `docs/transformers/image-vectorizer.md`

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by WinterSilence** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by andrewdalpino** [comment]
Hi @WinterSilence thanks alot for the submission! I seem to be missing something - can you show me the problem that this change fixes please?

Thanks, have a great day!

**Comment by WinterSilence** [comment]
@andrewdalpino 
https://github.com/RubixML/ML/blob/c8a28404a6f373f38ef681e1418e999c1eaab05e/src/Transformers/ImageVectorizer.php#L46

**Comment by andrewdalpino** [comment]
Right, the default value for this argument is `false`. Having that said, an example is just an example - it's meant to demonstrate how to instantiate an object of this class. I cannot find anything materially wrong with it either way.

**Comment by WinterSilence** [comment]
@andrewdalpino now passing the argument makes sense - no reason to pass default value

**Comment by andrewdalpino** [comment]
Haha, ok fair enough :)

**Review by andrewdalpino — APPROVED** [review]

**Pull request merged**
