### PR TITLE
Dynamic column width in console output

### PR DESCRIPTION
**Pull request by MacGruber91**
#### Summary

This PR added dynamic column size, by making the columns the same size.

Issue #79

### CODE REVIEW

**Comment by andrewdalpino** [comment]
Hey @MacGruber91 thanks alot! I won't have time alot of time to review this PR this month (hopefully we can get someone else) but just wanted to point you to our contributing guide beforehand. I noticed that you used an anonymous function, which we cannot use due to some limitations.

https://github.com/RubixML/ML/blob/master/CONTRIBUTING.md

**Comment by MacGruber91** [comment]
recheck

**Comment by MacGruber91** [comment]
recheck

**Comment by MacGruber91** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by andrewdalpino** [comment]
recheck

**Comment by andrewdalpino** [comment]
Hey @MacGruber91 I had a bit of time so I went ahead and pulled your branch to do a bit of testing ... nice work on the `table()` method, elegant solution I like it alot, but I didn't notice a way for the dataset object to dynamically adjust the *number* of columns to display. For example, if there are too many columns to fit within the terminal, we should show just enough to fit within the space provided. Is this something you've considered yet or did you just focus on the width?

Screenshot 2021-01-10 225531

P.S. Not sure why CLA bot isn't recognizing your digital signature, did you commit these changes under a different Git username?

**Comment by MacGruber91** [comment]
Hi @andrewdalpino! Yes, I was focused on dynamic column width. Sorry, I don't quite understand what you mean, because the number of columns is now dynamic. How I can reproduce your screenshot?

P.S. Thank you for the advice about CLA, I had the wrong commit signature

**Comment by andrewdalpino** [comment]
You know what, I tested it on a Windows machine with Git bash, I remember there might have been an issue with detecting the terminal size

I'll take another look soon

Were you able to resize your terminal and it adjust the number of columns automatically?

**Comment by MacGruber91** [comment]
Yes, when the terminal is resized, the number of columns changes dynamically. But I have a macOS

**Comment by MacGruber91** [comment]
Yes, you're right, getting the terminal size is different for Windows. We can do something like that:  [Symfony/Terminal](https://github.com/symfony/symfony/blob/v5.2.1/src/Symfony/Component/Console/Terminal.php#L87) 
But I can't check it, cause I don't have windows OS

**Comment by MacGruber91** [comment]
recheck

**Review by andrewdalpino — APPROVED** [review]
Thanks again @MacGruber91 nice work!

**Pull request merged**
