### PR TITLE
Update Sentence.php and SentenceTest.php

### PR DESCRIPTION
**Pull request by BahmanMehrdad**
The problem of using other languages such as Farsi and Arabic has been solved.

### CODE REVIEW

**Comment by andrewdalpino** [comment]
This is fantastic @BahmanMD thank you. I just want to do a bit more testing with other languages to make sure that we didn't break anything by making this change. If this change does not break backward compatibility then we'll release it with the next feature update, otherwise we'll have to release it with ML 3.0.

**Comment by andrewdalpino** [comment]
Ok, I also want to see how this affects performance since the regular expression used to match the sentences is more complex now.

**Comment by andrewdalpino** [comment]
Not sure why GitHub closed this PR, maybe because the target branch was deleted, but I can't figure out how to unclose it. You may have to resubmit a new PR and target the master branch.

**Comment by BahmanMehrdad** [comment]
@andrewdalpino  Sure.

**Comment by andrewdalpino** [comment]
Thank you @BahmanMD

**Pull request closed without merging**
